### ISSUE TITLE
Rotating point class doesn't rotate object in game

### ISSUE THREAD

**Issue by RetrocadeMedia** [QodotPlugin/qodot-plugin#147]
This could very well be me missing something, but I'm having some difficulty with rotating point classes. In Trenchbroom, when I rotate a point class it just displaces it around the origin, which I thought was just a strange quirk, but it also seems to do the same thing in Godot as well.

Am I missing some really obvious entity rotater? Is this an issue with Trenchbroom and I should take it up with them? And is there anything I can do about it for now other than just manually rotating and re-placing some objects in Godot?

**Comment by Shfty** [comment]
Entity rotations in quake maps are represented by the `angle` (yaw) and `mangle` (euler angles) properties. When you rotate an entity in TB it will write to one of those, prioritizing `mangle` if present, and creating `angle` if neither exists.

As with any other property, these are just key/value pairs that have no special behavior. Qodot purposefully takes an unopinionated approach here: As there are various non-transform ways to use those values, auto-applying them as rotations would be arbitrary.

Thus, how those values are used is the responsibility of the object receiving them.

If your object's script has an `export(Dictionary) var properties`, QodotMap will populate it at build time. You can mark your script as `tool` to allow it to run in-editor, and give that dictionary a `setget` setter in order to run logic when it gets written to. From there, it should be trivial to read from `properties["angle"]` / `properties["mangle"]` and set the appropriate transform values.
